name: Publish to WinGet
on:
  release:
    # A release was published, or a pre-release was changed to a release.
    # As this workflow only publishes and creates no assets, it can run when the release is published
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@main
        with:
          identifier: topgrade-rs.topgrade
          max-versions-to-keep: 5 # keep only latest 5 versions
          token: ${{ secrets.WINGET_TOKEN }}
